package adf.embers.tools;

import org.hsqldb.jdbc.JDBCDataSource;
import org.hsqldb.jdbcDriver;
import org.skife.jdbi.v2.DBI;
import org.skife.jdbi.v2.Handle;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class EmbersDatabase {

    public static final String JDBC_URL = "jdbc:hsqldb:mem:acceptance-test";
    private static final String USERNAME = "sa";
    private static final String PASSWORD = "";
    private final String jdbcUrl;
    private DataSource dataSource;

    public EmbersDatabase(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl;
    }

    public void startInMemoryDatabase() throws Exception {
        DriverManager.registerDriver(jdbcDriver.driverInstance);

        this.dataSource = new JDBCDataSource();
        ((JDBCDataSource) this.dataSource).setDatabase(jdbcUrl);
        ((JDBCDataSource) this.dataSource).setUser(USERNAME);
        ((JDBCDataSource) this.dataSource).setPassword(PASSWORD);
        this.dataSource.setLoginTimeout(5);
    }

    public void shutdownInMemoryDatabase() {
        try (Connection connection = getDataSource().getConnection()) {
            Statement st = connection.createStatement();
            st.execute("SHUTDOWN");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public DataSource getDataSource() {
        return dataSource;
    }

    public void createTableQueries() {
        Handle handle = new DBI(dataSource).open();
        handle.execute("CREATE TABLE queries(" +
                "id INTEGER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                "name VARCHAR(50)," +
                "description VARCHAR(1000)," +
                "sql VARCHAR(2000))");
        handle.close();
    }

}
