version: 2
jobs:
  build:
    working_directory: ~/alfanse/embers
    parallelism: 1
    docker:
    - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - run:
        working_directory: ~/alfanse/embers
        # for diagnostics, show me the version, includes JVM, and Gradle.
        command: ./gradlew --version
    # Build
    - run: ./gradlew build codeCoverageReport
    - store_test_results:
        path: embers-services/build/test-results
    - store_test_results:
        path: embers-acceptance-tests/build/test-results
    - store_test_results:
        path: embers-spring/build/test-results
    - store_artifacts:
        name: store embers-acceptance-tests reports
        path: embers-acceptance-tests/build/yatspec
        destination: yatspec
    - store_artifacts:
        name: store jacoco reports
        path: build/reports/jacoco
        destination: jacoco
